/**
 * English Test Question Database
 * Categories: Professional, Academic, Workplace
 * Generated by MindTest.id AI
 */

window.QUESTIONS_DB = {
    // -------------------------------------------------------------------------
    // 1. Professional (TOEIC® / IELTS General)
    // -------------------------------------------------------------------------
    professional: [
        // Grammar (1-20)
        { id: 1, type: "grammar", question: "Ms. Anderson ______ the sales report before the meeting started.", options: ["review", "reviews", "had reviewed", "will review"], correctAnswerIndex: 2 },
        { id: 2, type: "grammar", question: "We look forward ______ you at the upcoming conference.", options: ["to see", "to seeing", "seeing", "see"], correctAnswerIndex: 1 },
        { id: 3, type: "grammar", question: "The new software is ______ efficient than the old system.", options: ["much", "more", "very", "most"], correctAnswerIndex: 1 },
        { id: 4, type: "grammar", question: "Despite ______ late, he finished the presentation on time.", options: ["he was", "of being", "being", "be"], correctAnswerIndex: 2 },
        { id: 5, type: "grammar", question: "If I ______ you, I would accept the offer immediately.", options: ["was", "am", "were", "had been"], correctAnswerIndex: 2 },
        { id: 6, type: "grammar", question: "The CEO ______ the keynote speech at tomorrow's gala.", options: ["deliver", "is delivering", "delivered", "have delivered"], correctAnswerIndex: 1 },
        { id: 7, type: "grammar", question: "Please ensure that specific safety guidelines are ______ adhered to.", options: ["strict", "strictness", "strictly", "stricter"], correctAnswerIndex: 2 },
        { id: 8, type: "grammar", question: "Neither the manager ______ the employees were aware of the change.", options: ["or", "nor", "and", "but"], correctAnswerIndex: 1 },
        { id: 9, type: "grammar", question: "The deadline is approaching; we need to work ______ than usual.", options: ["hard", "harder", "hardly", "hardest"], correctAnswerIndex: 1 },
        { id: 10, type: "grammar", question: "By the time we arrive, the meeting ______ ended.", options: ["will have", "would have", "has", "had"], correctAnswerIndex: 0 },
        { id: 11, type: "grammar", question: "I suggest that he ______ the contract carefully.", options: ["review", "reviews", "reviewed", "reviewing"], correctAnswerIndex: 0 },
        { id: 12, type: "grammar", question: "______ of the weather, the outdoor event will proceed.", options: ["Regardless", "Regarding", "Regard", "Regards"], correctAnswerIndex: 0 },
        { id: 13, type: "grammar", question: "The shipment ______ yesterday has been damaged.", options: ["receive", "receiving", "received", "receives"], correctAnswerIndex: 2 },
        { id: 14, type: "grammar", question: "It is essential that everyone ______ on time.", options: ["be", "is", "are", "being"], correctAnswerIndex: 0 },
        { id: 15, type: "grammar", question: "We have worked here ______ five years.", options: ["since", "for", "during", "while"], correctAnswerIndex: 1 },
        { id: 16, type: "grammar", question: "The proposal ______ by the board next week.", options: ["was reviewed", "will be reviewed", "reviews", "has reviewed"], correctAnswerIndex: 1 },
        { id: 17, type: "grammar", question: "Can you tell me where ______?", options: ["the station is", "is the station", "the station be", "is station"], correctAnswerIndex: 0 },
        { id: 18, type: "grammar", question: "Upon ______ the office, please sign in at the front desk.", options: ["enter", "entered", "entering", "entrance"], correctAnswerIndex: 2 },
        { id: 19, type: "grammar", question: "He is capable ______ handling complex negotiations.", options: ["to", "of", "for", "in"], correctAnswerIndex: 1 },
        { id: 20, type: "grammar", question: "Unless we ______ more resources, the project will fail.", options: ["secure", "secured", "will secure", "securing"], correctAnswerIndex: 0 },

        // Vocabulary (21-35)
        { id: 21, type: "vocabulary", question: "Please ______ the attached document for the project details.", options: ["verify", "inspect", "review", "gaze"], correctAnswerIndex: 2 },
        { id: 22, type: "vocabulary", question: "The company's revenue has ______ significantly over the last quarter.", options: ["expanded", "increased", "inflated", "magnified"], correctAnswerIndex: 1 },
        { id: 23, type: "vocabulary", question: "We need to ______ a meeting to discuss the budget.", options: ["schedule", "occur", "invent", "locate"], correctAnswerIndex: 0 },
        { id: 24, type: "vocabulary", question: "The candidate possesses ______ experience in digital marketing.", options: ["expansive", "extensive", "extended", "expired"], correctAnswerIndex: 1 },
        { id: 25, type: "vocabulary", question: "Please ______ your receipt for reimbursement purposes.", options: ["retain", "remain", "reside", "return"], correctAnswerIndex: 0 },
        { id: 26, type: "vocabulary", question: "They reached a tentative ______ on the contract terms.", options: ["agree", "agreement", "agreeable", "agreed"], correctAnswerIndex: 1 },
        { id: 27, type: "vocabulary", question: "The seminar proved to be highly ______ for the new interns.", options: ["beneficial", "benefit", "beneficiary", "benefactor"], correctAnswerIndex: 0 },
        { id: 28, type: "vocabulary", question: "Unexpected ______ have delayed the construction project.", options: ["circumstances", "circumferences", "circles", "circulations"], correctAnswerIndex: 0 },
        { id: 29, type: "vocabulary", question: "Effective communication is ______ to our success.", options: ["vital", "vivid", "vocal", "valid"], correctAnswerIndex: 0 },
        { id: 30, type: "vocabulary", question: "We must ______ with international trade regulations.", options: ["comply", "compile", "compose", "compete"], correctAnswerIndex: 0 },
        { id: 31, type: "vocabulary", question: "The manager ______ the team for their hard work.", options: ["commanded", "commended", "commented", "commenced"], correctAnswerIndex: 1 },
        { id: 32, type: "vocabulary", question: "He was ______ to the position of Senior Vice President.", options: ["promote", "promoted", "promoting", "promotion"], correctAnswerIndex: 1 },
        { id: 33, type: "vocabulary", question: "Please ______ your application by Friday.", options: ["submit", "submitting", "submission", "submissive"], correctAnswerIndex: 0 },
        { id: 34, type: "vocabulary", question: "The results ______ our expectations.", options: ["exceeded", "executed", "excerpted", "excelled"], correctAnswerIndex: 0 },
        { id: 35, type: "vocabulary", question: "Currently, the position is ______.", options: ["vacant", "vacuum", "vacation", "vacate"], correctAnswerIndex: 0 },

        // Reading (36-50)
        { id: 36, type: "reading", question: "What is the main purpose of this email?", context: "Subject: Office Renovation Schedule\n\nDear Staff,\n\nPlease be advised that the west wing of the office will be closed for renovations starting next Monday, June 10th. Work is expected to last for two weeks. Employees seated in this area should temporarily relocate to Conference Room B.", options: ["To announce a holiday", "To inform staff of a closure", "To requested a meeting", "To hire new staff"], correctAnswerIndex: 1 },
        { id: 37, type: "reading", question: "Where should affected employees go?", context: "Subject: Office Renovation Schedule\n\nDear Staff,\n\nPlease be advised that the west wing of the office will be closed for renovations starting next Monday, June 10th. Work is expected to last for two weeks. Employees seated in this area should temporarily relocate to Conference Room B.", options: ["Home", "The east wing", "Conference Room B", "The cafeteria"], correctAnswerIndex: 2 },
        { id: 38, type: "reading", question: "How long will the renovation take?", context: "Subject: Office Renovation Schedule\n\nDear Staff,\n\nPlease be advised that the west wing of the office will be closed for renovations starting next Monday, June 10th. Work is expected to last for two weeks. Employees seated in this area should temporarily relocate to Conference Room B.", options: ["One week", "Two weeks", "One month", "Indefinitely"], correctAnswerIndex: 1 },
        { id: 39, type: "reading", question: "What is being announced?", context: "ANNOUNCEMENT: Due to inclement weather, the annual company picnic has been postponed. The new date is Saturday, August 15th. We apologize for any inconvenience.", options: ["A cancellation", "A promotion", "A postponement", "A new policy"], correctAnswerIndex: 2 },
        { id: 40, type: "reading", question: "When is the new date?", context: "ANNOUNCEMENT: Due to inclement weather, the annual company picnic has been postponed. The new date is Saturday, August 15th. We apologize for any inconvenience.", options: ["August 15th", "Tomorrow", "Next week", "Unknown"], correctAnswerIndex: 0 },
        { id: 41, type: "reading", question: "Who is the memo for?", context: "MEMO\nTo: Sales Team\nFrom: Director of Marketing\nRe: Q3 Targets\n\nGreat work meeting the Q2 goals. Let's aim even higher for Q3. A meeting will be held on Tuesday at 10 AM to discuss strategies.", options: ["The entire company", "The Marketing team", "The Sales Team", "The CEO"], correctAnswerIndex: 2 },
        { id: 42, type: "reading", question: "What will happen on Tuesday?", context: "MEMO\nTo: Sales Team\nFrom: Director of Marketing\nRe: Q3 Targets\n\nGreat work meeting the Q2 goals. Let's aim even higher for Q3. A meeting will be held on Tuesday at 10 AM to discuss strategies.", options: ["A party", "A holiday", "A meeting", "A deadline"], correctAnswerIndex: 2 },
        { id: 43, type: "reading", question: "What is changing?", context: "NOTICE TO TENANTS: The building entrance codes will be changed on the 1st of the month. Please collect your new key fob from the security desk.", options: ["The rent", "The entrance codes", "The security guard", "The building location"], correctAnswerIndex: 1 },
        { id: 44, type: "reading", question: "What must tenants do?", context: "NOTICE TO TENANTS: The building entrance codes will be changed on the 1st of the month. Please collect your new key fob from the security desk.", options: ["Pay money", "Call the police", "Collect a key fob", "Move out"], correctAnswerIndex: 2 },
        { id: 45, type: "reading", question: "What is the discount?", context: "SALE: For a limited time, enjoy 20% off all office furniture. Free shipping on orders over $500.", options: ["500%", "20%", "Free", "10%"], correctAnswerIndex: 1 },
        { id: 46, type: "reading", question: "How can you get free shipping?", context: "SALE: For a limited time, enjoy 20% off all office furniture. Free shipping on orders over $500.", options: ["Order any item", "Order over $500", "Be a member", "Pick up in store"], correctAnswerIndex: 1 },
        { id: 47, type: "reading", question: "What is NOT allowed?", context: "REMINDER: Smoking is strictly prohibited within 10 meters of the building entrance.", options: ["Eating", "Drinking", "Smoking near entrance", "Walking"], correctAnswerIndex: 2 },
        { id: 48, type: "reading", question: "What is the tone of the message?", context: "Dear Customer, Thank you for your feedback. We are investigating the issue and will resolve it shortly.", options: ["Angry", "Professional and polite", "Confused", "Sarcastic"], correctAnswerIndex: 1 },
        { id: 49, type: "reading", question: "Who sent the email?", context: "From: Tech Support\nTo: Employee\nSubject: Maintenance\n\nServer maintenance is scheduled for tonight at 11 PM.", options: ["Employee", "Tech Support", "HR", "The client"], correctAnswerIndex: 1 },
        { id: 50, type: "reading", question: "When is the maintenance?", context: "From: Tech Support\nTo: Employee\nSubject: Maintenance\n\nServer maintenance is scheduled for tonight at 11 PM.", options: ["Tomorrow morning", "Tonight at 11 PM", "Next week", "Now"], correctAnswerIndex: 1 },

        // Situational (51-60)
        { id: 51, type: "situational", question: "You missed a deadline due to unclarity. How do you respond to your manager?", options: ["It wasn't clear, so I didn't do it.", "I apologize. The instructions were unclear, so I paused to avoid errors. Can we clarify?", "You didn't explain it well.", "I will do it later."], correctAnswerIndex: 1 },
        { id: 52, type: "situational", question: "A customer is angry about a defective product. You say:", options: ["Please calm down.", "I apologize for the inconvenience. Let me arrange a replacement for you immediately.", "It works for everyone else.", "Call the manufacturer."], correctAnswerIndex: 1 },
        { id: 53, type: "situational", question: "A colleague asks for help, but you are busy. You say:", options: ["I can't right now.", "I'm occupied at the moment, but I can help you in an hour.", "Ask someone else.", "Go away."], correctAnswerIndex: 1 },
        { id: 54, type: "situational", question: "You are running late for a meeting. You message:", options: ["Running late.", "I'll be there in 10 minutes. Apologies for the delay.", "Start without me.", "Traffic is bad."], correctAnswerIndex: 1 },
        { id: 55, type: "situational", question: "You disagree with a coworker's idea. You say:", options: ["That's a bad idea.", "I see your point, but have you considered this alternative?", "I don't like it.", "Wrong."], correctAnswerIndex: 1 },
        { id: 56, type: "situational", question: "You need to decline an invitation politely. You say:", options: ["No.", "I can't make it.", "Thank you for the invite, but I have a prior commitment.", "Not interested."], correctAnswerIndex: 2 },
        { id: 57, type: "situational", question: "A client thanks you for good service. You respond:", options: ["You're welcome.", "No problem.", "It was my pleasure. Let us know if you need anything else.", "Okay."], correctAnswerIndex: 2 },
        { id: 58, type: "situational", question: "You didn't hear what someone said in a meeting. You say:", options: ["What?", "Repeat that.", "Could you please repeat that?", "I can't hear you."], correctAnswerIndex: 2 },
        { id: 59, type: "situational", question: "You are introducing yourself to a new team. You say:", options: ["Hi.", "I'm the new guy.", "Hello, I'm [Name], and I'm excited to join the team.", "Who are you?"], correctAnswerIndex: 2 },
        { id: 60, type: "situational", question: "You need to ask for a deadline extension. You say:", options: ["I need more time.", "Can I turn it in late?", "Would it be possible to extend the deadline to Friday?", "I won't finish."], correctAnswerIndex: 2 }
    ],

    // -------------------------------------------------------------------------
    // 2. Academic (IELTS Academic®)
    // -------------------------------------------------------------------------
    academic: [
        // Vocabulary in Context (1-10)
        { id: 1, type: "vocabulary", question: "The results of the experiment were ______ with previous studies.", options: ["constant", "consistent", "contested", "contained"], correctAnswerIndex: 1 },
        { id: 2, type: "vocabulary", question: "The professor emphasized the ______ necessity of rigorous methodology.", options: ["absolute", "abstract", "abundant", "absurd"], correctAnswerIndex: 0 },
        { id: 3, type: "vocabulary", question: "This theory is ______ on the assumption of rational behavior.", options: ["based", "basis", "basic", "basement"], correctAnswerIndex: 0 },
        { id: 4, type: "vocabulary", question: "We observed a ______ correlation between the two variables.", options: ["signify", "significant", "significance", "significantly"], correctAnswerIndex: 1 },
        { id: 5, type: "vocabulary", question: "The student provided a ______ explanation for the phenomenon.", options: ["plausible", "plausibility", "applause", "pause"], correctAnswerIndex: 0 },
        { id: 6, type: "vocabulary", question: "Funding was ______ to the research department.", options: ["allocated", "located", "relocated", "dislocated"], correctAnswerIndex: 0 },
        { id: 7, type: "vocabulary", question: "He made a ______ contribution to the field of physics.", options: ["subsist", "substantial", "substance", "substantiate"], correctAnswerIndex: 1 },
        { id: 8, type: "vocabulary", question: "The data was ______ from a variety of sources.", options: ["compile", "compiled", "compiling", "compilation"], correctAnswerIndex: 1 },
        { id: 9, type: "vocabulary", question: "Academic integrity is of ______ importance.", options: ["paramount", "mountain", "amount", "surmount"], correctAnswerIndex: 0 },
        { id: 10, type: "vocabulary", question: "The hypothesis was eventually ______ by new evidence.", options: ["verified", "verify", "verity", "verily"], correctAnswerIndex: 0 },

        // Grammar (11-20)
        { id: 11, type: "grammar", question: "Not only ______ the deadline, but he also submitted a flawless report.", options: ["did he meet", "he met", "met he", "he did meet"], correctAnswerIndex: 0 },
        { id: 12, type: "grammar", question: "Had I known about the lecture, I ______ attended.", options: ["would have", "will have", "would", "have"], correctAnswerIndex: 0 },
        { id: 13, type: "grammar", question: "The data, ______ was collected last year, is still relevant.", options: ["which", "that", "who", "whom"], correctAnswerIndex: 0 },
        { id: 14, type: "grammar", question: "______ being tired, she continued to study.", options: ["Despite", "Although", "Even", "However"], correctAnswerIndex: 0 },
        { id: 15, type: "grammar", question: "It is suggested that the student ______ the library more often.", options: ["use", "uses", "used", "using"], correctAnswerIndex: 0 },
        { id: 16, type: "grammar", question: "Rarely ______ satisfy everyone.", options: ["can a solution", "a solution can", "can solution", "solution can"], correctAnswerIndex: 0 },
        { id: 17, type: "grammar", question: "If the temperature ______, the reaction stops.", options: ["drops", "dropped", "dropping", "drop"], correctAnswerIndex: 0 },
        { id: 18, type: "grammar", question: "The number of applicants ______ increased recently.", options: ["has", "have", "having", "to have"], correctAnswerIndex: 0 },
        { id: 19, type: "grammar", question: "To ______ it may concern.", options: ["who", "whom", "whose", "which"], correctAnswerIndex: 1 },
        { id: 20, type: "grammar", question: "Neither the professor nor the students ______ happy with the schedule.", options: ["were", "was", "is", "be"], correctAnswerIndex: 0 },

        // Critical Reasoning (21-30)
        { id: 21, type: "reasoning", question: "Select the most logical inference from: 'Students sleeping <6 hours perform 20% worse.'", options: ["Math is hard.", "Sleep deprivation may negatively impact performance.", "All students should sleep 10 hours.", "Students perform better at night."], correctAnswerIndex: 1 },
        { id: 22, type: "reasoning", question: "Which weakens the argument: 'Electric cars reduce pollution, so buy one.'", options: ["Electric cars are expensive.", "Battery production produces toxic waste.", "Cars are fast.", "Gas is cheap."], correctAnswerIndex: 1 },
        { id: 23, type: "reasoning", question: "If A implies B, and B implies C, then:", options: ["A implies C", "C implies A", "A equals C", "B is false"], correctAnswerIndex: 0 },
        { id: 24, type: "reasoning", question: "What acts as a premise in an argument?", options: ["The conclusion", "The evidence or reason", "The counter-argument", "The question"], correctAnswerIndex: 1 },
        { id: 25, type: "reasoning", question: "Identify the assumption: 'She is a lawyer, so she must be wealthy.'", options: ["All lawyers are wealthy.", "She is smart.", "Lawyers work hard.", "Wealth is good."], correctAnswerIndex: 0 },
        { id: 26, type: "reasoning", question: "Which follow logic? All men are mortal. Socrates is a man.", options: ["Socrates is mortal.", "Socrates is a god.", "Men are Socrates.", "Mortals are men."], correctAnswerIndex: 0 },
        { id: 27, type: "reasoning", question: "Critique: 'Everyone is doing it, so it must be right.' This is:", options: ["A valid argument", "The bandwagon fallacy", "A scientific fact", "A legal defense"], correctAnswerIndex: 1 },
        { id: 28, type: "reasoning", question: "Cause and effect: Ice melts when heated.", options: ["Heating causes melting.", "Melting causes heating.", "Ice creates heat.", "Heat creates ice."], correctAnswerIndex: 0 },
        { id: 29, type: "reasoning", question: "Main idea: 'Solar energy is clean but expensive to store.'", options: ["Solar is perfect.", "Storage cost is a drawback of solar.", "Solar is dirty.", "Energy is free."], correctAnswerIndex: 1 },
        { id: 30, type: "reasoning", question: "Inference: 'The lights are off and the door is locked.'", options: ["Someone is inside.", "The business is likely closed.", "It is daytime.", "The door is broken."], correctAnswerIndex: 1 },

        // Reading (31-50)
        { id: 31, type: "reading", question: "What is Neuroplasticity?", context: "Neuroplasticity refers to the brain's ability to reorganize itself by forming new neural connections throughout life.", options: ["Brain damage", "The brain's adaptability", "Nerve death", "Fixed connections"], correctAnswerIndex: 1 },
        { id: 32, type: "reading", question: "When does it occur?", context: "Neuroplasticity refers to the brain's ability to reorganize itself by forming new neural connections throughout life.", options: ["Childhood only", "Throughout life", "In old age only", "Never"], correctAnswerIndex: 1 },
        { id: 33, type: "reading", question: "What does Climate Change affect?", context: "Climate change refers to long-term shifts in temperatures and weather patterns. These shifts may be natural, but since the 1800s, human activities have been the main driver of climate change, primarily due to burning fossil fuels like coal, oil and gas.", options: ["Temperature only", "Weather patterns and temperature", "Human activities", "Fossil fuels"], correctAnswerIndex: 1 },
        { id: 34, type: "reading", question: "What is the main driver since 1800s?", context: "Climate change (passage above)", options: ["Natural shifts", "Human activities", "Solar flares", "Volcanoes"], correctAnswerIndex: 1 },
        { id: 35, type: "reading", question: "What defines a Black Hole?", context: "A black hole is a region of spacetime where gravity is so strong that nothing—no particles or even electromagnetic radiation such as light—can escape from it.", options: ["Weak gravity", "No light can escape", "A bright star", "A wormhole"], correctAnswerIndex: 1 },
        { id: 36, type: "reading", question: "What is inflation?", context: "Inflation is the rate at which the general level of prices for goods and services is rising and, consequently, the purchasing power of currency is falling.", options: ["Falling prices", "Rising purchasing power", "Rising prices", "Stable currency"], correctAnswerIndex: 2 },
        { id: 37, type: "reading", question: "What happens to purchasing power during inflation?", context: "Inflation (passage above)", options: ["It rises", "It stays the same", "It falls", "It doubles"], correctAnswerIndex: 2 },
        { id: 38, type: "reading", question: "DNA contains what?", context: "Deoxyribonucleic acid (DNA) is a molecule composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms.", options: ["Genetic instructions", "Proteins only", "Blood", "Sugar"], correctAnswerIndex: 0 },
        { id: 39, type: "reading", question: "What shape is DNA?", context: "DNA (passage above)", options: ["Single strand", "Triple loops", "Double helix", "Square"], correctAnswerIndex: 2 },
        { id: 40, type: "reading", question: "What was the Renaissance?", context: "The Renaissance was a fervent period of European cultural, artistic, political and economic 'rebirth' following the Middle Ages.", options: ["A war", "A period of rebirth", "The dark ages", "An economic crash"], correctAnswerIndex: 1 },
        { id: 41, type: "reading", question: "What is Photosynthesis?", context: "Photosynthesis is the process used by plants, algae and certain bacteria to harness energy from sunlight and turn it into chemical energy.", options: ["Eating food", "Sleeping", "Harnessing sunlight energy", "Burning carbon"], correctAnswerIndex: 2 },
        { id: 42, type: "reading", question: "Who uses photosynthesis?", context: "Photosynthesis (passage above)", options: ["Humans", "Plants and algae", "Animals", "Rocks"], correctAnswerIndex: 1 },
        { id: 43, type: "reading", question: "What is the primary function of the heart?", context: "The heart is a muscular organ in most animals, which pumps blood through the blood vessels of the circulatory system.", options: ["To digest food", "To pump blood", "To think", "To move limbs"], correctAnswerIndex: 1 },
        { id: 44, type: "reading", question: "What system does the heart belong to?", context: "Heart (passage above)", options: ["Nervous system", "Digestive system", "Circulatory system", "Skeletal system"], correctAnswerIndex: 2 },
        { id: 45, type: "reading", question: "What is AI?", context: "Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence displayed by humans or animals.", options: ["Human thought", "Machine intelligence", "Animal instinct", "A computer game"], correctAnswerIndex: 1 },
        { id: 46, type: "reading", question: "What is Natural Selection?", context: "Natural selection is the differential survival and reproduction of individuals due to differences in phenotype.", options: ["Choosing a mate", "Survival due to differences", "Random chance", "Nature walks"], correctAnswerIndex: 1 },
        { id: 47, type: "reading", question: "What causes tides?", context: "Tides are the rise and fall of sea levels caused by the combined effects of the gravitational forces exerted by the Moon and the Sun, and the rotation of the Earth.", options: ["Wind", "Gravitational forces", "Fish", "Boats"], correctAnswerIndex: 1 },
        { id: 48, type: "reading", question: "What are fossil fuels?", context: "Fossil fuels are made from decomposing plants and animals. These fuels are found in the Earth's crust and contain carbon and hydrogen, which can be burned for energy.", options: ["Renewable energy", "Decomposed matter", "Nuclear waste", "Solar panels"], correctAnswerIndex: 1 },
        { id: 49, type: "reading", question: "What is the Water Cycle?", context: "The water cycle describes the continuous movement of water on, above and below the surface of the Earth.", options: ["Water staying still", "Continuous movement of water", "Rain only", "Ocean tides"], correctAnswerIndex: 1 },
        { id: 50, type: "reading", question: "Where does water move?", context: "Water cycle (passage above)", options: ["Only in the ocean", "On, above, and below Earth", "Only in space", "Underground only"], correctAnswerIndex: 1 }
    ],

    // -------------------------------------------------------------------------
    // 3. Workplace (TOEIC®-style)
    // -------------------------------------------------------------------------
    workplace: [
        // Sentence Completion (1-15)
        { id: 1, type: "sentence-completion", question: "All travel expenses must be ______ by Friday.", options: ["submit", "submitted", "submitting", "submission"], correctAnswerIndex: 1 },
        { id: 2, type: "sentence-completion", question: "Mr. Lee is responsible ______ training new interns.", options: ["for", "to", "with", "of"], correctAnswerIndex: 0 },
        { id: 3, type: "sentence-completion", question: "The conference room is located ______ the second floor.", options: ["on", "at", "in", "to"], correctAnswerIndex: 0 },
        { id: 4, type: "sentence-completion", question: "Please ______ the manual before operating the machine.", options: ["reads", "reading", "read", "reader"], correctAnswerIndex: 2 },
        { id: 5, type: "sentence-completion", question: "We need to hire ______ administrative assistant.", options: ["a", "an", "the", "two"], correctAnswerIndex: 1 },
        { id: 6, type: "sentence-completion", question: "The package was ______ yesterday.", options: ["deliver", "delivered", "delivering", "delivery"], correctAnswerIndex: 1 },
        { id: 7, type: "sentence-completion", question: "He is the ______ person for the job.", options: ["good", "better", "best", "well"], correctAnswerIndex: 2 },
        { id: 8, type: "sentence-completion", question: "Please ______ me if you cannot attend.", options: ["notify", "note", "notice", "notification"], correctAnswerIndex: 0 },
        { id: 9, type: "sentence-completion", question: "The meeting will start ______ 9:00 AM.", options: ["on", "in", "at", "for"], correctAnswerIndex: 2 },
        { id: 10, type: "sentence-completion", question: "We offered him the job, ______ he declined.", options: ["so", "but", "or", "and"], correctAnswerIndex: 1 },
        { id: 11, type: "sentence-completion", question: "The prices are ______ high.", options: ["too", "to", "two", "tow"], correctAnswerIndex: 0 },
        { id: 12, type: "sentence-completion", question: "Make sure to ______ your computer.", options: ["lock", "locked", "locking", "locks"], correctAnswerIndex: 0 },
        { id: 13, type: "sentence-completion", question: "She works ______ than anyone else.", options: ["hard", "harder", "hardest", "hardly"], correctAnswerIndex: 1 },
        { id: 14, type: "sentence-completion", question: "The printer is out ______ paper.", options: ["of", "off", "from", "for"], correctAnswerIndex: 0 },
        { id: 15, type: "sentence-completion", question: "We look forward to ______ from you.", options: ["hear", "hearing", "heard", "hears"], correctAnswerIndex: 1 },

        // Error Recognition (16-25)
        { id: 16, type: "error-recognition", question: "Error: 'The team discuss the project yesterday.'", options: ["The", "discuss", "project", "yesterday"], correctAnswerIndex: 1 },
        { id: 17, type: "error-recognition", question: "Error: 'She have been working here for two years.'", options: ["She", "have", "working", "here"], correctAnswerIndex: 1 },
        { id: 18, type: "error-recognition", question: "Error: 'Please sending the file immediately.'", options: ["Please", "sending", "the", "immediately"], correctAnswerIndex: 1 },
        { id: 19, type: "error-recognition", question: "Error: 'I look forward to meet you.'", options: ["look", "forward", "to", "meet"], correctAnswerIndex: 3 },
        { id: 20, type: "error-recognition", question: "Error: 'He is capable to do the job.'", options: ["He", "is", "capable", "to do"], correctAnswerIndex: 3 },
        { id: 21, type: "error-recognition", question: "Error: 'Despite it was raining, we went out.'", options: ["Despite", "it was", "raining", "went"], correctAnswerIndex: 0 },
        { id: 22, type: "error-recognition", question: "Error: 'The informations is incorrect.'", options: ["The", "informations", "is", "incorrect"], correctAnswerIndex: 1 },
        { id: 23, type: "error-recognition", question: "Error: 'She don't like coffee.'", options: ["She", "don't", "like", "coffee"], correctAnswerIndex: 1 },
        { id: 24, type: "error-recognition", question: "Error: 'Where is the station is?'", options: ["Where", "is", "the", "station is"], correctAnswerIndex: 3 },
        { id: 25, type: "error-recognition", question: "Error: 'I am agree with you.'", options: ["I", "am", "agree", "with"], correctAnswerIndex: 1 },

        // Short Reading (26-35)
        { id: 26, type: "reading", question: "What is mandatory?", context: "NOTICE: Safety boots must be worn in the warehouse.", options: ["Gloves", "Boots", "Hats", "Vests"], correctAnswerIndex: 1 },
        { id: 27, type: "reading", question: "When is the deadline?", context: "Please submit expenses by Friday at 5 PM.", options: ["Thursday", "Friday 5PM", "Next week", "Now"], correctAnswerIndex: 1 },
        { id: 28, type: "reading", question: "What is broken?", context: "Out of Order: The elevator is currently under maintenance. Please use the stairs.", options: ["The stairs", "The elevator", "The door", "The lights"], correctAnswerIndex: 1 },
        { id: 29, type: "reading", question: "Where to go?", context: "Delivery drivers: Please use the rear entrance.", options: ["Front door", "Side door", "Rear entrance", "Lobby"], correctAnswerIndex: 2 },
        { id: 30, type: "reading", question: "Who to call?", context: "For IT support, dial extension 404.", options: ["HR", "IT Support", "Sales", "Manager"], correctAnswerIndex: 1 },
        { id: 31, type: "reading", question: "What is the new hour?", context: "Store hours have changed. We now open at 8 AM.", options: ["9 AM", "8 AM", "7 AM", "10 AM"], correctAnswerIndex: 1 },
        { id: 32, type: "reading", question: "Is lunch provided?", context: "Join us for the workshop. Lunch will be provided.", options: ["No", "Yes", "Maybe", "Bring your own"], correctAnswerIndex: 1 },
        { id: 33, type: "reading", question: "What is prohibited?", context: "No parking in the loading zone.", options: ["Walking", "Loading", "Parking", "Driving"], correctAnswerIndex: 2 },
        { id: 34, type: "reading", question: "What is the fee?", context: "Late payment fee: $25.", options: ["$10", "$20", "$25", "$50"], correctAnswerIndex: 2 },
        { id: 35, type: "reading", question: "How to apply?", context: "Apply online at our website.", options: ["Call", "Email", "Visit", "Online"], correctAnswerIndex: 3 },

        // Situational (36-40)
        { id: 36, type: "situational", question: "Coworker: 'I'm swamped.' You:", options: ["Good luck.", "Can I help?", "Work faster.", "Too bad."], correctAnswerIndex: 1 },
        { id: 37, type: "situational", question: "Phone rings. You answer:", options: ["What?", "Speak.", "Hello, [Company Name], how can I help you?", "Who is this?"], correctAnswerIndex: 2 },
        { id: 38, type: "situational", question: "Leaving a voicemail. You say:", options: ["Call me.", "It's [Name].", "Hi, this is [Name]. Please call me back at [Number].", "Bye."], correctAnswerIndex: 2 },
        { id: 39, type: "situational", question: "Late to work. You say:", options: ["Traffic.", "I apologize for being late.", "I'm here now.", "It happens."], correctAnswerIndex: 1 },
        { id: 40, type: "situational", question: "Meeting ending. You say:", options: ["Done.", "Thank you everyone.", "Bye.", "Finally."], correctAnswerIndex: 1 }
    ]
};
